# Generated by Django 4.2.16 on 2025-01-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pretixbase", "0276_item_hidden_if_item_available_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="hidden_if_item_available_mode",
            field=models.CharField(default="hide", max_length=16),
        ),
    ]
